export default [
    {
        "ProductID": 1,
        "ProductName": "Chai",
        "UnitPrice": 18,
        "UnitsInStock": 39,
        "DeliveryOn": new Date(1996, 8, 20),
        "Currency" : "EUR",
        "Rating" : 3,
        "Image" : "img/1.jpg",
    },
    {
        "ProductID": 2,
        "ProductName": "Chang",
        "UnitPrice": 19,
        "UnitsInStock": 17,
        "DeliveryOn": new Date(1996, 7, 12),
        "Currency" : "EUR",
        "Rating" : 4,
        "Image" : "img/2.jpg",
    },
    {
        "ProductID": 3,
        "ProductName": "Aniseed Syrup",
        "UnitPrice": 10,
        "UnitsInStock": 0,
        "DeliveryOn": new Date(1996, 8, 26),
        "Currency" : "EUR",
        "Rating" : 5,
        "Image" : "img/3.jpg",
    },
    {
        "ProductID": 4,
        "ProductName": "Chef Anton's Cajun Seasoning",
        "UnitPrice": 22,
        "UnitsInStock": 53,
        "DeliveryOn": new Date(1996, 9, 19),
        "Currency" : "EUR",
        "Rating" : 0,
        "Image" : "img/4.jpg",
    },
    {
        "ProductID": 5,
        "ProductName": "Chef Anton's Gumbo Mix",
        "UnitPrice": 21.35,
        "UnitsInStock": 0,
        "DeliveryOn": new Date(1996, 7, 17),
        "Currency" : "EUR",
        "Rating" : 1,
        "Image" : "img/5.jpg",
    },
    {
        "ProductID": 6,
        "ProductName": "Grandma's Boysenberry Spread",
        "UnitPrice": 25,
        "UnitsInStock": 120,
        "DeliveryOn": new Date(1996, 9, 19),
        "Currency" : "EUR",
        "Rating" : 2,
        "Image" : "img/6.jpg",
    },
    {
        "ProductID": 7,
        "ProductName": "Uncle Bob's Organic Dried Pears",
        "UnitPrice": 30,
        "UnitsInStock": 0,
        "DeliveryOn": new Date(1996, 7, 22),
        "Currency" : "EUR",
        "Rating" : 3,
        "Image" : "img/7.jpg",
    },
    {
        "ProductID": 8,
        "ProductName": "Northwoods Cranberry Sauce",
        "UnitPrice": 40,
        "UnitsInStock": 0,
        "DeliveryOn": new Date(1996, 11, 1),
        "Currency" : "EUR",
        "Rating" : 4,
        "Image" : "img/8.jpg",
    },
    {
        "ProductID": 9,
        "ProductName": "Mishi Kobe Niku",
        "UnitPrice": 97,
        "UnitsInStock": 29,
        "DeliveryOn": new Date(1997, 1, 21),
        "Currency" : "EUR",
        "Rating" : 5,
        "Image" : "img/9.jpg",
    },
    {
        "ProductID": 10,
        "ProductName": "Ikura",
        "UnitPrice": 31,
        "UnitsInStock": 31,
        "DeliveryOn": new Date(1996, 8, 5),
        "Currency" : "EUR",
        "Rating" : 3,
        "Image" : "img/10.jpg",
    }
];